// Font import
import { montserrat } from "./fonts/fonts";
import type { Metadata } from "next";
import "./globals.css";
// Toast notification setup
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Application Metadata
export const metadata: Metadata = {
  title: "MediWave App",
  description: "Generated by create next app",
};

// RootLayout component wraps the entire application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        {children}
        {/* Global Toast Container for notifications */}
        <ToastContainer
          position="top-right"
          autoClose={6000}
          hideProgressBar
          closeOnClick
          pauseOnHover
          draggable
          theme="dark"
        />
      </body>
    </html>
  );
}
